### ISSUE TITLE
knitting issues

### ISSUE THREAD

**Issue by AaronGullickson** [Bdreon/xhamster-project#2]
@Bdreon 

I got your email and I took a look. There were two problems in the main.Rmd file.

1. You put your name in the wrong place in the header information. It goes next to `name` not `author`. 
2. You are just using fences ( \`\`\`) to enclose R code. To make it an R code chunk you need to use the {} bracket syntax. Look at the OLS regression project for examples.

I fixed the issues and pushed my results back to GH in commit f1599c2749e639ed60a83970bd320831eccbf1d4 with a few comments. It knits fine now. I also had to run `organize_data.R` to get the `analyticalData.RData` because you had not pushed that. Its possible that this will cause issues when you try to pull because it will conflict with your version. In that case, just delete your copy of `output/analyticalData.RData` before pulling.

**Comment by Bdreon** [comment]
Thank you! R Markdown for some reason is just not clicking for me very well. I have updated the analysis markdown file for the lab notebook exercise, and the changes to the knit on the main rmd mostly worked; the one outstanding issue with it is it attempts to display both of the graphs I print on one line, which makes the second graph run off the line. I tried to insert white space, but none of the solutions I thought of worked.

The reason I didn't include the analytical data RData file before was because I had initially tried to push it when I started working with the data weeks ago, and had saved it as a CSV which was way over the size limit. Obviously I corrected this for the final upload, but when I was committing and pushing for some reason it didn't click that now the file was under the 100mb limit, so I didn't commit it. I have now committed and pushed the analytical RData with the last commit.
